outerSpace/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :systems
  resources :ships

end

outerSpace/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

outerSpace/app/models/ship.rb
class Ship < ApplicationRecord
  validates :name, :velocity, presence: true
  belongs_to :system,
  class_name: 'System',
  foreign_key: :system_id,
  primary_key: :id
end

outerSpace/app/models/system.rb
class System < ApplicationRecord
  validates :name, :radius, presence: true

  has_many :ships,
  foreign_key: :system_id,
  class_name: 'Ship',
  primary_key: :id
end

outerSpace/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

outerSpace/app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  def new
    @ship = Ship.new
    render :new
  end

  def create
    ship = Ship.new(ship_params)
    if ship.save
      redirect_to ship_url(ship)
    else
      flash[:errors] = ship.errors.full_messages
    end
  end


  def show
    @ship = Ship.find(params[:id])
    render :show
  end

  def edit
    @ship = Ship.find(params[:id])
    render :edit
  end

  def update
    @ship = Ship.find(params[:id])
   if @ship.update(ship_params)
     redirect_to ship_url(@ship)
   else
     flash.now[:errors] = @ship.errors.full_messages
     render :edit
   end
  end


  def ship_params
    params.require(:ship).permit(:name,:velocity,:system_id)
  end
end

outerSpace/app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  def new
    @system = System.new
    render :new
  end

  def create
  @system = System.new(system_params)
  if @system.save
    redirect_to system_url(@system)
  else
      flash.now[:errors] = @system.errors.full_messages
      render :new
    end
  end
  def index
    @systems = System.all
    render :index
  end
  def show
    @system = System.find(params[:id])
    render :show
  end
  def update
    @system = System.find(params[:id])
   if @system.update(system_params)
     redirect_to system_url(@system)
   else
     flash.now[:errors] = @system.errors.full_messages
     render :edit
   end
  end
  def edit
    @system = System.find(params[:id])
    render :edit
  end

  def system_params
    params.require(:system).permit(:name,:radius)
  end
end

outerSpace/app/helpers/application_helper.rb
module ApplicationHelper
end

outerSpace/app/helpers/ships_helper.rb
module ShipsHelper
end

outerSpace/app/helpers/systems_helper.rb
module SystemsHelper
end

outerSpace/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OuterSpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:errors] %>
        <p><%= flash[:errors].join(", ") %></p>
      <% end %>
      <a href="<%= new_system_url %>">Create New System</a>
        <a href="<%= new_ship_url %>">Create New Ship</a>

    <%= yield %>
  </body>
</html>

outerSpace/app/views/ships/edit.html.erb
<h2>New Ship</h2>

<form action="<%= ship_url(@ship) %>" method="post">
 <input type="hidden" name="_method" value="patch">

  <label>
    Name
    <input type="text" name="ship[name]" value="<%= @ship.name %>" id="name">
  </label>
<<br>
  <label>
    Velocity
    <input type="number" name="ship[velocity]" value="<%= @ship.velocity %>" id="Velocity">
  </label>
  <select  name="ship[system_id]">
        <% System.all.each do |system| %>
            <option

                value="<%= system.id %>">
                <%= system.name %>
            </option>
        <% end %>
    </select>
<br>
  <input type="submit" value="Update ship">
</form>

outerSpace/app/views/ships/new.html.erb
<h2>New Ship</h2>

<form action="<%= ships_url %>" method="post">


  <label>
    Name
    <input type="text" name="ship[name]" value="<%= @ship.name %>" id="name">
  </label>
<br>
  <label>
    Velocity
    <input type="number" name="ship[velocity]" value="<%= @ship.velocity %>" id="Velocity">
  </label>
  <br>
  <label>
    System:
  <select  name="ship[system_id]">
        <% System.all.each do |system| %>
            <option

                value="<%= system.id %>">
                <%= system.name %>
            </option>
        <% end %>
    </select>
    </label>
<br>
  <input type="submit" value="Create New ship">
</form>

outerSpace/app/views/ships/show.html.erb
<h1>Ship Details</h1>
<h3>Name: <%= @ship.name %></h3>
<h3>Velocity: <%= @ship.velocity %></h3>
<h3>System: <%= @ship.system.name %></h3>

outerSpace/app/views/systems/index.html.erb
<h2>All Systems</h2>
<% @systems.each do |system| %>
<ul>
  System:<a href="<%= system_url(system) %>"><%= system.name %></a>
  <br>
     <% system.ships.each do |ship| %>
        <li><%= ship.name%></li>
        <% end %>

</ul>
<% end %>

outerSpace/app/views/systems/new.html.erb
<h2>New System</h2>

<form action="<%= systems_url %>" method="post">


  <label>
    Name
    <input type="text" name="system[name]" value="<%= @system.name %>" id="name">
  </label>
<br>
  <label>
    Radius
    <input type="number" name="system[radius]" value="<%= @system.radius %>" id="radius">
  </label>
<br>
  <input type="submit" value="Create New System">
</form>

outerSpace/app/views/systems/show.html.erb
<h1><%= @system.name%></h1>
 <% @system.ships.each do |ship| %>
 <li><a href="<%= ship_url(ship) %>"><%= ship.name %></a>
  <a href="<%= edit_ship_url(ship)%>">Edit</a
 </li>
 <% end %>